# Generated by Django 4.1.3 on 2023-01-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221227_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('user_list_view', 'Просмотр всех пользователей')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
