# Generated by Django 4.1.3 on 2022-12-23 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_remove_project_author_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(default=1, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
