# Generated by Django 4.1.3 on 2022-12-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
